In [2]:
from __future__ import print_function
import torch

In [3]:
result = torch.empty(5, 3)

In [4]:
result

tensor([[0.0000e+00, 4.6566e-10, 0.0000e+00],
        [4.6566e-10, 4.7339e+30, 1.7885e+22],
        [1.7743e+28, 2.0535e-19, 2.7909e+23],
        [6.2608e+22, 4.7428e+30, 4.4656e+30],
        [3.4731e-12, 1.7743e+28, 9.4701e-01]])

In [6]:
result[:,1]

tensor([4.6566e-10, 4.7339e+30, 2.0535e-19, 4.7428e+30, 1.7743e+28])

In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [45]:
y = x * 2
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<MulBackward0>)


In [46]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[24., 24.],
        [24., 24.]], grad_fn=<MulBackward0>) tensor(24., grad_fn=<MeanBackward1>)


In [47]:
out.backward()

In [48]:
print(x.grad)

tensor([[34.5000, 34.5000],
        [34.5000, 34.5000]])


In [64]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([1196.6687, 1125.5874,  340.5219], grad_fn=<MulBackward0>)


In [65]:
v = torch.tensor([10, 10, 10], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([10240., 10240., 10240.])


In [66]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
